Fix demo equipment search regression after 9122a87 (#258)
when typing charcters in the search top bar, the app crashes with:

Uncaught TypeError: getNameOrId is not a function
    getEquipmentsInfosForSearchBar EquipmentType.js:120
    getEquipmentsInfosForSearchBar EquipmentType.js:119
    searchEquipments EquipmentSearchBar.js:139
    searchMatchingEquipments app.js:299
    handleSearchTermChange element-search-dialog.js:40
    onInputChange element-search-dialog.js:71
    handleInputChange useAutocomplete.js:775
    handleChange InputBase.js:356